### ISSUE TITLE
Miner f022142 stats update.

### ISSUE THREAD

**Issue by NSC-FIL** [application-research/file.app#1]
The data is outdated on https://file.app/ for miner f022142.
Please update the information as found on-chain today:
Power : 87.38 TiB
Free space 84.87 TiB
Used space 3.274 TiB

It would be great if the data could be sorted by Location and refreshed more often as my miner continues to grow in storage capacity and number of deals.  Many thanks.

**Comment by jimmylee** [comment]
We rely on our APIs for this data, I'll try to get to the bottom of this.
